# Generated by Django 2.1 on 2019-08-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snippets', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
    ]
