# Generated by Django 2.1 on 2019-08-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snippets', '0002_remove_post_total_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
