# Generated by Django 2.1 on 2019-09-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snippets', '0005_like_count_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_views', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete='CASCADE', to='Snippets.Post')),
            ],
        ),
    ]
