# Generated by Django 2.1 on 2019-09-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snippets', '0006_viewpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='default_count',
            field=models.IntegerField(default=0),
        ),
    ]
